### ISSUE TITLE
much fucking

### ISSUE THREAD

**Issue by rattkin** [jakubboucek/fucking-eu-cookies#10]
super nápad, ale šlo by to bez toho fucking? seriozní projekty a tak dále.
Asi si to stáhnu a nahradím fucking -> efing pomocí search&destroy

**Comment by jakubboucek** [comment]
Díky, šlo by to, už jsem o tom i uvažoval, ale když vidím kolik seriózních projektů to nasadilo v současné podobě, tak jsem spokojen. Ale klidně si udělej fork, rád se o něm v projektu zmíním, pokud budeš včas přebírat update z upstreamu.

**Comment by jakubboucek** [comment]
Issue zavírám, protože dále není důvod, proč by měla být otevřena. 
@rattkin: pokud [svůj fork](https://github.com/rattkin/fucking-eu-cookies) dokončíte a vypublikujete, rád jej uvedu v dokumentaci a doporučím jej webům, které již nyní ze stejného důvodu používají vlastními silami cenzurovanou verzi.
