### ISSUE TITLE
Nevkládat do head

### ISSUE THREAD

**Issue by spernica** [jakubboucek/fucking-eu-cookies#11]
Ahoj, 

chci jen upozornit, že pokud vložíš javascript do <head> bude se brát text z tohoto javascriptu do vyhledávačů jako description ("Tento web používá ...") - pokud tedy nemáš description přímo definované sám. Lepší je tvůj vložit těsně před konec </body>. 

Pokud bys se mnou souhlasil, bylo by vhodné tohle upravit v dokumentaci doplňku, aby se to nestalo i ostatním.

**Comment by jakubboucek** [comment]
Ahoj, to, co tvrdíš, není tak úplně pravda, rspt. zaměňuješ příčiny důsledků. Tedy, ledaže bych špatně pochopil tvoje slova.

Tedy, pro začátek: Chápu správně, že namítáš, aby se tag `<script ...>`, kterým se lišta do stránky natahuje, nevkládala do `<head>`?

**Comment by spernica** [comment]
Omlouvám se za nejasnosti, abych to uvedl na pravou míru:

```
<html>
<head>

<!-- pokud kód vložíme sem, Google si vezme větu "Tento web používá ..." jako description -->
<script src="//d2z9iq901qkqk8.cloudfront.net/cz.js" async></script>
</head>
<body>

<!-- doporucuju vlozit sem -->
</body>
</html>
```

Samotného mě to překvapilo, ale je to tak... viz hledání na google:

![image](https://user-images.githubusercontent.com/16540723/27000071-43f89b98-4da9-11e7-9225-d9c07d63e218.png)

edit: našel jsem k tomu ještě tento zajímavý zdroj
https://centrical.com/test/google-json-ld-and-javascript-crawling-and-indexing-test.html

**Comment by jakubboucek** [comment]
Děkuji za upřesnění. Žel se tím ale potvrdilo tvoje nepochopení technologie a způsobu, jak je lišta do stránky vkládána.

Umístění značky `<script ...>` nemá na obsah vyrenedrované stránky vliv.

Google pro účely indexace nezkoumá obsah zdrojového kódu v podobě, v jaké je stažen. Natož, aby zkoumal a vyzobával texty ze scriptů. 

Google se zabývá obsahem DOM vyrenderované stránky, tedy stránky, která se sestavila z původního zdrojového kódu a násedně byla modifikovaná pomocí Javascriptu. A právě úprava DOMu pomocí JavaScriptu je touto lištou prováděna.

[Jak je uváděno v dokumentaci](https://github.com/jakubboucek/fucking-eu-cookies#umístění-lišty-v-kódu), lišta se ve výchozím stavu [vkládá na začátek `body`](https://github.com/jakubboucek/fucking-eu-cookies/blob/master/source/cookies.js#L83) a toto chování lze upravit konfigurací. Ve stém případě tedy stačí před `<script>` načítající lištu vložit:
```javascript
<script>
	var fucking_eu_config = {
		"options": {
			"insertTo": "body-end"
		}
	};
</script>
<script src="//d2z9iq901qkqk8.cloudfront.net/cz.js" async></script>
```

Pohlednutím na DOM stránky Salmondo je vidět, že lišta je na začátku `<body>` i přes vložení `<script>` tagu na konec.
![DOM stránky Salmondo](https://user-images.githubusercontent.com/1657322/27000788-0e711638-4dba-11e7-8dbe-56412a7d0349.png)

Umístění scritů na konec `<body>` se doporučuje především historicky z důvodu zrychlení vykreslování stránky, to je však nyní již překonáno příznaky [`async`](https://developer.mozilla.org/en/docs/Web/HTML/Element/script#attr-async) a [`defer`](https://developer.mozilla.org/en/docs/Web/HTML/Element/script#attr-defer), které lišta používá. Případně se pak umístění na konec stránky doporučovalo jako jednoduchý způsob, že v době spuštění scriptu bude načten celý DOM, což lišta řeší [modernějším způsobem](https://github.com/jakubboucek/fucking-eu-cookies/blob/master/source/cookies.js#L47).

V moderních prohlížečích umístění scriptu na konec stránky nemohu doporučit, protože pak se zdrojové kódy lišty začnou načítat později, přenosová linka i výpočetní kapacity klienta jsou využity neefektivně, což v důsledku způsobí větší prodlevu, než se lišta na stránce objeví. 

K indexaci Google bych měl ještě připomínku: Google zobrazuje začátek stránky jen v situaci, že:
- Vyhledávanému dotazu na stránce nic neodpovídá, aby to mohl použít v citaci
- Stránka neobsahuje [meta description](https://yoast.com/meta-descriptions/) 
- Struktura stránky prohlížeči nepomáhá zjistit kde začíná obsah stránky (všimněte si, že [některé stránky](https://www.google.cz/search?q=site%3Asalmondo.cz) s nadpisy vrací lepší odpovědi)

Pak tedy mohu jen doporučit stránky vylepšit:
- Do stránky vložit `<meta name="descritpion" ...>` s krátkým shrnutím, které čtenáři o firmě/stránce řeknou pár slov,
- Stránku trochu struktualizovat, zejména pomocí nadpisů `<h1 - h6>`

Ale není třeba se tím tolik trápit, protože přes vyhledávač se k Vám lidi dostanou většinou na nějaký konkrétní dotaz, díky kterému pak Google ze stránky vyzobne obsah, který odpovídá hledanému dotazu ([příklad](https://www.google.cz/search?q=Podmínky+služby+Salmondo)).

Uznávám ale, že výchozí chování lišty mohlo být trochu lepší - ale ale už není možné změnit kvůli BC, lištu používají stovky možná tisíce webů. Naštěstí existuje množství způsobů, jak si lze její chování modifikovat.
