### ISSUE TITLE
Kill CDN

### ISSUE THREAD

**Issue by jakubboucek** [jakubboucek/fucking-eu-cookies#12]
**tl;dr:** Chci ukončit stávající hosting projektu (CDN) a nabídnou jej pouze ke stažení.

Provoz této lišty na CDN v Amazonu ročně vyjde odhadem na 3 000 Kč. Jen za září 2017 lišta vygenerovala 6 660 762 HTTP(S) requestů, které v souhrnu znamenaly přenos dat v řádu 10  GB. A i když už boom kolem EU lišt pominul, její uplatnění stále roste, což náklady ještě půběžně zvyšuje. 

Mám za to, že jsem pro optimalizaci kódu a CDN udělal maximum (minifikace, cachování, omezení requestů). Jsou další možnosti vylepšení, ale už jen na vrub základních vlastností projektu, ze kterých nechci slevovat.

Řešením by také mohlo být převedení lišty na vlastní doménu, takže by se mohl v budoucnu hosting měnit bez nutnosti zásahu na straně webů, které ji používají. Ale tuto možnost jsem zavrhnul z důvodů:

1. Nemám žádnou doménu, kterou bych považoval k takovému účelu vhodnou a nepovažuju za vhodné další kupovat,
2. V minulosti [už jednu změnu hostující adresy projekt zažil](https://github.com/jakubboucek/fucking-eu-cookies/commit/868c55138b3104f4c90eb9abef529b185c641f82) a nerad bych vytvořil další BC, u kterého by navíc ani nabylo jisté, že bude definitivní,
3. Hostovat projekt na doménách vlastněných přímo společností Amazon vnímám jako jeden z velkých benefitů pro bezpečnost. Nasazením vlastní domény vzniká nezanedbatelné riziko, že po případném opuštění projektu (nebo z jiných, např. zdravotních důvodů) doména expiruje a ohrozí tak stovky webů.

Protože už více jak rok je lišta beze změny a nemám ve výhledu žádnou úpravu, není už hosting na CDN důležitý jako v době vývoje kvůli.

Jsem si vědom, že existují CDN pro open source projekty (např. [jsDelivr](https://www.jsdelivr.com/) nebo [cdnjs](https://cdnjs.com/)). Explicitní název projektu mu jejich využití nedovoluje a rebrandovat už ho nemíním. Je tu tak prostor pro ostattní na vytvoření smysluplného forku (rád jej doporučením podpořím).

## Závěrem
I když je to jen _pitomá lišta_, tak pro mne to byl velký projekt, zejména od okamžiku, kdy ji začaly použivat stovky webů. Hodně mě to naučilo, nelituju času ani peněz. Ale už stačí :)

Projekt sklízí kritiku ([příklad](https://twitter.com/0ndras/status/894517706392838144)) za svůj vyhraněný název. Plně se ztotožňuju s názorem, že je to neprofesionální. K tomu ale dodávám, že lišta nevznikala jako profesionální projekt, ale jako reakce na jiné podobné projekty, které IMHO měly zbytečně složitou implementaci do stránky a dělal jsem ji pro své potřeby. Její následná popularizace mne pak zaskočila nepřipraveného.

Nicméně jsem přesvědčený, že právě slovo „Fucking“ v názvu lišty nemalou měrou přispělo k její poplarizaci. I přesto si ale některá studia projekt před nasazením upravili s jediným záměrem – zbavit se toho slova (například: [100+1](http://historie.stoplusjednicka.cz/), [Svobodní](https://www.nemuzeme.cz/) a [jeden fork](https://github.com/brand-new/fucking-eu-cookies)). Z toho důvodu nebudu tuto verzi více propagovat.

**Comment by MartinKolarik** [comment]
Len pre info, jsDelivr po novom automaticky podporuje všetky projekty na npm a GitHube, takže názov nie je problém. Stačí spraviť release v ktorom budú aj dist súbory a bude to dostupné na `https://cdn.jsdelivr.net/gh/user/repo@version/file`.

**Comment by jakubboucek** [comment]
@MartinKolarik Díky, o tom jsem nevěděl. Přesto bych byl rád, aby se v dalším rozvoji popularizovala už varianta bez _fucking_ v názvu.

**Comment by potty** [comment]
Můžete využít CDN `https://cdn.jsdelivr.net/npm/eu-cookie-law`, jen místo `fucking` je použito `smart`.

**Comment by liborjelinek** [comment]
Nazev fucking by mizet nemel. Prijde mi to jako kapitulace. Dokud muzem na EU v EU nadavat, je to jeste dobre.

**Comment by jakubboucek** [comment]
Replaced by #14.
