### ISSUE TITLE
Button is not working correctly when is `insertTo` defined as ID in DOM.

### ISSUE THREAD

**Issue by jakubboucek** [jakubboucek/fucking-eu-cookies#8]
CZ: Podle feedbacku způsobuje lišta blíže nespecifikovanou chybu v JS při stisku tlačítka Souhlasím, je-li umístěna do stránky pomocí ID definovaného v DOM. 

Zjistil: Lumír Toman (www.websource.cz)

**Comment by adambisek** [comment]
Same issue.
When clicked button, it causes this error:
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Chrome 47.0.2526.106, OSX 10.11

**Comment by jakubboucek** [comment]
@adambisek : Test this beta pls. https://s3-eu-west-1.amazonaws.com/fucking-eu-cookies/beta/index.html It was stupid bug :-/

So, thank to error-message, i was some trouble to simulate of bug :-/

**Comment by adambisek** [comment]
@jakubboucek yep, this works correctly

**Comment by jakubboucek** [comment]
Hotfix is deployed to production but because browser cache is set by `Cache-control: public, max-age=604800` to one week your users can still keep old cached version with a bug. You can enforce it by call .js library with querystring `?v=0.1.9`. 
For example: https://s3-eu-west-1.amazonaws.com/fucking-eu-cookies/cz.js?v=0.1.9
